### ISSUE TITLE
media-video/davinci-resolve cannot start, log4cxx error.

### ISSUE THREAD

**Issue by wilburluo** [vowstar/vowstar-overlay#11]
when run command /opt/resolve/bin/resolve: 

`ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0

ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
log4cxx: No appender could be found for logger (BtCommon).
log4cxx: Please initialize the log4cxx system properly.
17.4.0.0012 Linux/Clang x86_64
Main thread starts: 6EEC55C0
log4cxx: setFile(./logs/rollinglog.txt,true) call failed.
log4cxx: IO Exception : status code = 13
0x7fec6eec55c0 | Undefined            | INFO  | 2022-05-01 09:04:16,084 | --------------------------------------------------------------------------------
log4cxx: No output stream or file set for the appender named [RollLogAppender].
0x7fec6eec55c0 | Undefined            | INFO  | 2022-05-01 09:04:16,084 | Loaded log config from /home/rowe/.local/share/DaVinciResolve/configs/log-conf.xml
0x7fec6eec55c0 | Undefined            | INFO  | 2022-05-01 09:04:16,084 | --------------------------------------------------------------------------------
[1]    30909 segmentation fault (core dumped)  /opt/resolve/bin/resolve`

**Comment by vowstar** [comment]
I tried to reproduce this problem on my computer, but it is normal on my computer, here is my log:

```bash
~ /opt/resolve/bin/resolve
ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
log4cxx: No appender could be found for logger (BtCommon).
log4cxx: Please initialize the log4cxx system properly.
17.4.0.0012 Linux/Clang x86_64
Main thread starts: DF8075C0
log4cxx: setFile(./logs/rollinglog.txt,true) call failed.
log4cxx: IO Exception : status code = 13
0x7fb3df8075c0 | Undefined            | INFO  | 2022-05-02 12:17:29,870 | --------------------------------------------------------------------------------
log4cxx: No output stream or file set for the appender named [RollLogAppender].
0x7fb3df8075c0 | Undefined            | INFO  | 2022-05-02 12:17:29,871 | Loaded log config from /home/vowstar/.local/share/DaVinciResolve/configs/log-conf.xml
0x7fb3df8075c0 | Undefined            | INFO  | 2022-05-02 12:17:29,871 | --------------------------------------------------------------------------------
Resolve communication is open and waiting..
Accepted new client
FusionScript Server [17877] Started
Host 'Fusion' [16783] Added

```

And then it shows the GUI.

![Screenshot from 2022-05-02 12-33-30](https://user-images.githubusercontent.com/394260/166184682-128c87ef-78b3-4eaf-82a9-feb371666d5b.png)

My hardware:

CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A


After my investigation, I found that many people have the same problem on different linux distributions, 
https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=56878&start=950

I guess it may be related to the graphics card and the graphics card driver.
https://askubuntu.com/questions/1201835/davinci-resolve-not-starting-aborted-core-dumped

> DaVinci Resolve requires an NVIDIA graphics card on Linux and the original NVIDIA drivers. Nouveau drivers aren't supported.

**Comment by wilburluo** [comment]
> I tried to reproduce this problem on my computer, but it is normal on my computer, here is my log:
> 
> ```shell
> ~ /opt/resolve/bin/resolve
> ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
> ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
> ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
> ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
> PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
> log4cxx: No appender could be found for logger (BtCommon).
> log4cxx: Please initialize the log4cxx system properly.
> 17.4.0.0012 Linux/Clang x86_64
> Main thread starts: DF8075C0
> log4cxx: setFile(./logs/rollinglog.txt,true) call failed.
> log4cxx: IO Exception : status code = 13
> 0x7fb3df8075c0 | Undefined            | INFO  | 2022-05-02 12:17:29,870 | --------------------------------------------------------------------------------
> log4cxx: No output stream or file set for the appender named [RollLogAppender].
> 0x7fb3df8075c0 | Undefined            | INFO  | 2022-05-02 12:17:29,871 | Loaded log config from /home/vowstar/.local/share/DaVinciResolve/configs/log-conf.xml
> 0x7fb3df8075c0 | Undefined            | INFO  | 2022-05-02 12:17:29,871 | --------------------------------------------------------------------------------
> Resolve communication is open and waiting..
> Accepted new client
> FusionScript Server [17877] Started
> Host 'Fusion' [16783] Added
> ```
> 
> And then it shows the GUI.
> 
> ![Screenshot from 2022-05-02 12-33-30](https://user-images.githubusercontent.com/394260/166184682-128c87ef-78b3-4eaf-82a9-feb371666d5b.png)
> 
> My hardware:
> 
> CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
> 
> After my investigation, I found that many people have the same problem on different linux distributions, https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=56878&start=950
> 
> I guess it may be related to the graphics card and the graphics card driver. https://askubuntu.com/questions/1201835/davinci-resolve-not-starting-aborted-core-dumped
> 
> > DaVinci Resolve requires an NVIDIA graphics card on Linux and the original NVIDIA drivers. Nouveau drivers aren't supported.

I am running nvidia optimus laptop with i5-7300hp and Nvida GeForce GTX 1050 Ti Mobile, using nvidia-drivers-510.60.02 and disabled nouveau drivers in kernel config.

**Comment by vowstar** [comment]
What is the result of your nvidia-smi output?

**Comment by wilburluo** [comment]
![nvidia-smi](https://user-images.githubusercontent.com/42597219/166439182-b0e2e55c-701f-45b5-8a40-3625633e9106.png)

**Comment by vowstar** [comment]
By https://wiki.archlinux.org/title/DaVinci_Resolve, 
It looks like your hardware configuration should be able to run this software.
Suspicion may be Optimius Manager.
See also: https://www.reddit.com/r/davinciresolve/comments/kueov0/davinci_resolve_will_not_start_on_optimus_nvidia/
From https://aur.archlinux.org/packages/davinci-resolve,
> After Ages of debugging and trying multiple solutions and having multiple errors one of them is submitted by johnjohn , I found the solutions 👇
> 
> 1) make sure that your drivders are correct according to this : https://wiki.archlinux.org/title/DaVinci_Resolve
> 
> 2) if you have Nvidia card with Optimius Manager installed make sure you have it set to Nvidia mode , not integrated or hybrid [!IMPORTANT]
> 
> 3) run it in sudo using the following command [Nvidia card ]: sudo prime-run /opt/resolve/bin/resolve $u
> 
> it gives me this error when trying to run it without sudo !!!!
> ```
> ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
> ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
> ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
> ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
> PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
> 17.4.4.0007 Linux/Clang x86_64
> Main thread starts: 590495C0
> 0x7fc4590495c0 | Undefined            | INFO  | 2022-03-07 18:30:17,713 | --------------------------------------------------------------------------------
> 0x7fc4590495c0 | Undefined            | INFO  | 2022-03-07 18:30:17,714 | Loaded log config from /home/egyleader/.local/share/DaVinciResolve/configs/log-conf.xml
> 0x7fc4590495c0 | Undefined            | INFO  | 2022-03-07 18:30:17,714 | --------------------------------------------------------------------------------
> /bin/prime-run: line 2: 48556 Segmentation fault      (core dumped) __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
>```


I don't have the same hardware environment as you, so I can only guess, and more debugging information may be needed to help you.

Could you see some abnormal info in ``dmesg``?

https://wiki.archlinux.org/title/DaVinci_Resolve#Logs_location

DaVinci Resolve creates log file `$HOME/.local/share/DaVinciResolve/logs/ResolveDebug.txt` at every launch. 
Could you see some useful information from this file? 
The following information can be seen under normal startup:

```
0x7fb3df8075c0 | Main.GPUConfig       | INFO  | 2022-05-02 12:17:30,179 | Compute API set to automatic, defaulting to CUDA.
0x7fb3df8075c0 | Main.GPUConfig       | INFO  | 2022-05-02 12:17:30,179 | Selected compute API: CUDA
0x7fb3df8075c0 | Main.GPUConfig       | INFO  | 2022-05-02 12:17:30,179 | Automatic GPU Selection:
0x7fb3df8075c0 | Main.GPUConfig       | INFO  | 2022-05-02 12:17:30,180 |   - "NVIDIA GeForce RTX 2080 Ti"
```

If you use an incompatible mode, the graphics card detection will fail, and ``dmesg`` may have a segfault in ``pipe_iris.so``.

**Comment by wilburluo** [comment]
Maybe i misconfiged the nvidia driver, i reinstalled gentoo recently, and decide move from xfce to kde plasma and install exactly the same nvidia driver, then davinci started without any problem, so i think maybe i misconfiged or maybe it's xfce's bug?
