### ISSUE TITLE
media-video/davinci-resolve: disk space requirements for build

### ISSUE THREAD

**Issue by pask2** [vowstar/vowstar-overlay#13]
Hello!

For me, media-video/davinci-resolve used about 14gb of disk space in /var/tmp/portage when building. On the first emerge this caused me to run out of space and the build failed (my SSD is a bit small).

I think the ebuild could benefit from a disk space requirement before the build, as this would cause the emerge to cancel and complain instead of trying to build and then running out of storage.

There is an eclass for this that could be useful: [check-reqs.eclass](https://devmanual.gentoo.org/eclass-reference/check-reqs.eclass/index.html) - an example of usage here: [mail-client/thunderbird/thunderbird-102.6.0::gentoo, line 377](https://gitweb.gentoo.org/repo/gentoo.git/tree/mail-client/thunderbird/thunderbird-102.6.0.ebuild#n377)

Please let me know if I'm completely out of touch here or if this is a stupid idea, or if I'm the only one who has had this issue :)

**Comment by vowstar** [comment]
This is a very good suggestion, thanks for the reminder.
I packaged sci-mathematics/mathematica and did the same.
I'll improve the davinci-resolve package soon.
