### ISSUE TITLE
media-video/davinci-resolve fails to start (WITH FIX) also probably affects media-video/davinci-resolve-studio

### ISSUE THREAD

**Issue by ryanknutson** [vowstar/vowstar-overlay#17]
resolve fails to start and gives error
```
symbol lookup error: /usr/lib64/libpango-1.0.so.0: undefined symbol: g_string_free_and_steal
```

I did some searching and found that Reddit user [vetinari](https://www.reddit.com/user/vetinari/) had discovered a solution. I tested, and can confirm the fix works on Gentoo. [Here is a link to their original comment.](https://www.reddit.com/r/Fedora/comments/12g0mh4/comment/jgv7631/?utm_source=share&utm_medium=web2x&context=3)

> The issue is, that resolve brings it's own glib2, but not it's own pango. It uses system-provided pango, which in turn assumes newer glib2 than resolve's.
> 
> The workaround is to move all glib2 libraries out of /opt/resolve/libs to somewhere else (/opt/resolve/libs/_disabled, for example). After that, resolve will pick system-provided glib2 and pango will be happy with that."

The fix is to create a "disabled" folder in `/opt/resolve/libs/_disabled/` and move the following files into it:
> libgio*, libglib*, libgmodule*, libgobject*

This will disable the broken bundled libs and instead use working system ones.

**Comment by vowstar** [comment]
https://github.com/vowstar/vowstar-overlay/commit/887d8d7da41951de56eee56a599851ae9a4af63f

bumped to 18.6.2 and applied fix
