### ISSUE TITLE
Nvidia Container Toolkit Fails checksum verification

### ISSUE THREAD

**Issue by peteches** [vowstar/vowstar-overlay#2]
Hi, I've just tried install the nvidia container toolkit from your overlay, but I'm running into some trouble.

libnvidia-container installs finem but the checksums don't match the download, for either v1.1.1 or v1.1.2.

`
2020-07-18 16:48:53 (2.87 MB/s) - ‘/var/cache/distfiles/nvidia-container-toolkit-1.1.1.tar.gz.__download__’ saved [1767996]

!!! Fetched file: nvidia-container-toolkit-1.1.1.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      1767996
!!! Expected: 1768013
Refetching... File renamed to '/var/cache/distfiles/nvidia-container-toolkit-1.1.1.tar.gz._checksum_failure_.6t89_j6d'`

And

`2020-07-18 16:55:31 (727 KB/s) - ‘/var/cache/distfiles/nvidia-container-toolkit-1.1.2.tar.gz.__download__’ saved [1744451]

!!! Fetched file: nvidia-container-toolkit-1.1.2.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      1744451
!!! Expected: 1744445
Refetching... File renamed to '/var/cache/distfiles/nvidia-container-toolkit-1.1.2.tar.gz._checksum_failure_.tanunibo'
`
Many Thanks

**Comment by peteches** [comment]
Looking deeper it appears that NVIDIA have moved their repo from `NVIDIA/container-toolkit` to `NVIDIA/nvidia-container-toolkit` and re-packaged the tarball. There is a 301 in place from the old archive to the new, but the ebuild is failing because the packages are no longer the same. The new tarball extracts to a nvidia-container-toolkit dir instead of container-toolkit the ebuild expects.

I'm new to ebuilds, but I may be able to get a PR for you to fix this. :crossed_fingers:

**Comment by vowstar** [comment]
Thank you!
