### ISSUE TITLE
sci-electronics/kicad-*9999 set KEYWORDS outside conditional

### ISSUE THREAD

**Issue by doctaweeks** [vowstar/vowstar-overlay#4]
The kicad live ebuilds should not set KEYWORDS outside the PV == 9999 conditional.

**Comment by vowstar** [comment]
> The kicad live ebuilds should not set KEYWORDS outside the PV == 9999 conditional.

As [Gentoo devmanual\[1\]](https://devmanual.gentoo.org/ebuild-writing/functions/src_unpack/vcs-sources/index.html) said:

> Note: VCS ebuilds must be with empty KEYWORDS but not package.masked (except if the mask is for an independent reason). Usually the KEYWORDS line should be omitted altogether. This applies to "live" ebuilds (-9999) and to ebuilds that extract a static revision but still use a version control system for fetching.

Every time I use the pkgcheck command to check whether my ebuilds meets the gentoo specification. To fit it, KEYWORDS must outside the PV == 9999 conditional.

The workaround is:

Put these line into ``/etc/portage/package.accept_keywords/kicad``
```bash
# Using latest version of kicad
=sci-electronics/kicad-9999 **
=sci-electronics/kicad-footprints-9999 **
=sci-electronics/kicad-i18n-9999 **
=sci-electronics/kicad-packages3d-9999 **
=sci-electronics/kicad-symbols-9999 **
=sci-electronics/kicad-templates-9999 **

```

[1]https://devmanual.gentoo.org/ebuild-writing/functions/src_unpack/vcs-sources/index.html

**Comment by doctaweeks** [comment]
> Every time I use the pkgcheck command to check whether my ebuilds meets the gentoo specification. To fit it, KEYWORDS must outside the PV == 9999 conditional.

You must be running a broken version of pkgcheck. The ebuilds you have are wrong. It should *never* be necessary for a user to mask live packages to prevent them from installing.

If you use a working version of pkgcheck it will report the the error for every single one of those packages:

sci-electronics/kicad-i18n
  VisibleVcsPkg: version 9999: VCS version visible for KEYWORDS="~amd64", profile default/linux/amd64/17.0/x32 (54 total)

sci-electronics/kicad-footprints
  VisibleVcsPkg: version 9999: VCS version visible for KEYWORDS="~amd64", profile default/linux/amd64/17.0/x32 (54 total)

sci-electronics/kicad-packages3d
  VisibleVcsPkg: version 9999: VCS version visible for KEYWORDS="~amd64", profile default/linux/amd64/17.0/x32 (32 total)

sci-electronics/kicad-symbols
  VisibleVcsPkg: version 9999: VCS version visible for KEYWORDS="~amd64", profile default/linux/amd64/17.0/x32 (54 total)

sci-electronics/kicad-templates
  VisibleVcsPkg: version 9999: VCS version visible for KEYWORDS="~amd64", profile default/linux/amd64/17.0/x32 (54 total)

**Comment by vowstar** [comment]
@doctaweeks Thank you, I understand what you mean, the duplicate KEYWORDS should remove
