### ISSUE TITLE
octave-ocl emerge failed with wrong directory

### ISSUE THREAD

**Issue by stelinux01** [vowstar/vowstar-overlay#7]
Hi Huang,
I try to emerge octave-ocl but emerge stop at prepare phase:

Emerging (1 of 1) sci-mathematics/octave-ocl-1.1.1::vowstar
Failed to emerge sci-mathematics/octave-ocl-1.1.1, Log file:
'/var/tmp/portage/sci-mathematics/octave-ocl-1.1.1/temp/build.log'
Jobs: 0 of 1 complete, 1 failed                 Load avg: 1.08, 0.52, 0.48
Package:    sci-mathematics/octave-ocl-1.1.1
Repository: vowstar
Maintainer: vowstar@gmail.com
USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
Unpacking source...
Unpacking octave-ocl-1.1.1.tar.gz to /var/tmp/portage/sci-mathematics/octave-ocl-1.1.1/work
Source unpacked in /var/tmp/portage/sci-mathematics/octave-ocl-1.1.1/work
>>> ERROR: sci-mathematics/octave-ocl-1.1.1::vowstar failed (prepare phase):
>>> The source directory '/var/tmp/portage/sci-mathematics/octave-ocl-1.1.1/work/ocl-1.1.1' doesn't exist**

Call stack:
   ebuild.sh, line  809:  Called __ebuild_main 'prepare'
   phase-functions.sh, line 1059:  Called __dyn_prepare
  phase-functions.sh, line  385:  Called die
 The specific snippet of code:
 die "The source directory '${S}' doesn't exist"
 

emerge create /var/tmp/portage/sci-mathematics/octave-ocl-1.1.1/work/ocl directory loosing -1.1.1
if I correct by manual emerge the process complete successfully.

**Comment by vowstar** [comment]
Fixed in https://github.com/vowstar/octave-gentoo-package/commit/e0b47555a75ea45e14195c3451d3924b605e705e script, all the octave ebuilds updated, please update and try again.
