### ISSUE TITLE
nvidia-container-toolkit-1.7.0 patch unexpectedly ends in middle of line

### ISSUE THREAD

**Issue by SigHunter** [vowstar/vowstar-overlay#9]
Hi, thank you for the overlay and nvidia-container-toolkit ebuild. 
I have 1.5.0 installed and it's working fine in my containers. 
On upgrade to 1.7.0 the build fails while patching: 

```
* Applying nvidia-container-toolkit-1.5.0-gosum.patch ...
patching file go.sum
patch unexpectedly ends in middle of line
Hunk #1 FAILED at 471.
1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
```

I deleted the file nvidia-container-toolkit-1.5.0-gosum.patch, redownloaded it but issue persists

full build log: 
https://dpaste.com/5VQ5F3FQN

**Comment by vowstar** [comment]
This bug has been fixed, please try again

**Comment by SigHunter** [comment]
it's fixed, thanks!
